### ISSUE TITLE
"System error" response from pasted code

### ISSUE THREAD

**Issue by ErikEklund** [Canny1913/miunlock#18]
I tried logging in and pasting the code in the code.txt file in the console. The response was this:

`&&&START&&&{"code":10001,"result":"error","desc":"系统错误","description":"系统错误"}`

The desc / description translates to "System error". I have changed my username / password in the pasted code. Any suggestions for what might cause this appreciated.

**Comment by tfuxu** [comment]
. The desc / description translates to "System error"
System error? It was probably a internal error on the Xiaomi auth server side, because `strings.py` has this as a description for error 10001:
```
Internal error (sig verif fail)
```
It should now work, as I was able to retrieve full response 5 minutes ago.

**Comment by ErikEklund** [comment]
Hm, I tried again and still getting the same error message. Does this require any specific settings on your account, or other prerequisites? I'm also using my phone as username (in the format "+<countrycode><number>"), same as I can successfully log into the account with. Can ofc be server side issues again, but logging in normally with the same credentials work just fine.

**Comment by ErikEklund** [comment]
Ok some slight progress.. I tried a few times more and got the same issue. This was on my Linux desktop running Arch. I decided to try on my Macbook instead, where I got another response. It looked like this:

`&&&START&&&{"notificationUrl":"https://account.xiaomi.com/identity/authStart?sid=passport&context=(long string)&_locale=en&_old=true","result":"ok","code":0,"captchaUrl":null,"description":"成功","location":"","securityStatus":16,"pwd":0,"child":0,"desc":"成功"}`

Pasting this response into the script, it says that I need to verify my Xiaomi account and a link to follow to do so. Verifying the account gives the response:

`{"R":"","S":"OK"}`

If I try to run the code.txt script again, I get the same response (different context, but the python script still says I need to start the verification process). I'm not entirely sure what needs to be verified here, I have verified my email connected to the account as well. There doesn't seem to be any option to verify anything else on the account.

**Comment by tfuxu** [comment]
> 

I'm not sure if it will work in your case, but you need to tick "Trust this device" checkbox.
![Screenshot from 2022-08-30 23-26-31](https://user-images.githubusercontent.com/73042332/187546654-3344fdc2-17c8-47a0-ad22-e492b8d1d815.png)

After that, copy JS injection again to console, and you should get a full response.

**Comment by ErikEklund** [comment]
I tried again, opened the link, and authenticated again, this time making sure the "trust this device" was checked. After successful authentication, I re-ran the script and got the same challenge. Very strange. Tried with both email and sms verification, but the "trust this device" does not seem to work. Might be something on my end, add blocker interfering, or my browser (chrome). Also not sure why the styling on the challenge is different to yours.

Anyway, exhausted all my attempts now, so will have to try again tomorrow. Thanks for the help so far.

<img width="476" alt="Screenshot 2022-08-30 at 23 54 38" src="https://user-images.githubusercontent.com/1064329/187551022-e64bd1cc-19b5-4385-b57c-39b27c9c1567.png">

**Comment by tfuxu** [comment]
You can try disabling custom DNS or VPN, I've read that someone had issues with binding account in `OEM unlocking` when they had VPN turned on, so maybe the same issue is here. You could also check if this issue persist with different account.

**Comment by ErikEklund** [comment]
Tried with a different account, and that worked. Ofc, the phone is not bound to this account so I got

`ERROR:root:invalid code != 0: {'code': 20031, 'description': '请在MIUI上绑定账号后解锁：开发者模式下打开设置，搜索设备解锁状态，然后进行绑定', 'descCN': '请在MIUI上绑定账号后解锁：开发者模式下打开设置，搜索设备解锁状态，然后进行绑定', 'descEN': "Please add your account in MIUI's Settings > Developer options > Mi Unlock status.", 'uid': '...'}

request.XiaomiError: [ERROR]: Device is not bound to Xiaomi account. Please add it in the developer settings and try again
`

..which I can not do as the phone is not bootable. Anyway, it seems as there is something up with the original account and not with the script, so closing this ticket. Thanks for the help.
